import type { PortFamily } from '../primitives/index.js';

export type PortCapability = `${string}:${string}`;

const cap = <T extends readonly PortCapability[]>(...values: T): T => values;

export const PORT_FAMILY_CAPABILITIES = {
  FinanceAccounting: cap(
    'account:read',
    'journal:read',
    'journal:write',
    'invoice:read',
    'invoice:write',
    'bill:read',
    'bill:write',
    'vendor:read',
    'reconciliation:write',
    'report:read',
  ),
  PaymentsBilling: cap(
    'charge:read',
    'charge:write',
    'refund:write',
    'subscription:read',
    'subscription:write',
    'invoice:read',
    'invoice:write',
    'payment-method:read',
    'payout:write',
    'balance:read',
  ),
  ProcurementSpend: cap(
    'po:read',
    'po:write',
    'po:approve',
    'expense:read',
    'expense:write',
    'expense:approve',
    'vendor:read',
    'vendor:write',
    'rfq:write',
    'contract:read',
  ),
  HrisHcm: cap(
    'employee:read',
    'employee:write',
    'department:read',
    'position:read',
    'time-off:read',
    'time-off:write',
    'benefit:read',
    'org:read',
  ),
  Payroll: cap(
    'payroll:read',
    'payroll:write',
    'payroll:approve',
    'paystub:read',
    'tax:read',
    'schedule:read',
    'deduction:read',
    'earning:read',
    'contractor:read',
  ),
  CrmSales: cap(
    'party:read',
    'party:write',
    'company:read',
    'company:write',
    'opportunity:read',
    'opportunity:write',
    'pipeline:read',
    'activity:read',
    'activity:write',
    'note:read',
    'note:write',
  ),
  CustomerSupport: cap(
    'ticket:read',
    'ticket:write',
    'ticket:assign',
    'agent:read',
    'comment:read',
    'comment:write',
    'tag:read',
    'tag:write',
    'kb:read',
    'sla:read',
    'csat:read',
  ),
  ItsmItOps: cap(
    'incident:read',
    'incident:write',
    'change:read',
    'change:write',
    'change:approve',
    'asset:read',
    'asset:write',
    'cmdb:read',
    'problem:read',
    'problem:write',
    'sr:read',
  ),
  IamDirectory: cap(
    'user:read',
    'user:write',
    'group:read',
    'group:write',
    'role:read',
    'role:write',
    'app:read',
    'auth:write',
    'mfa:write',
    'audit:read',
  ),
  SecretsVaulting: cap(
    'secret:read',
    'secret:write',
    'secret:rotate',
    'cert:read',
    'cert:write',
    'crypto:read',
    'crypto:write',
    'key:read',
    'key:write',
    'audit:read',
    'policy:write',
  ),
  MarketingAutomation: cap(
    'contact:read',
    'contact:write',
    'list:read',
    'list:write',
    'campaign:read',
    'campaign:write',
    'campaign:send',
    'stats:read',
    'automation:read',
    'automation:write',
    'form:read',
  ),
  AdsPlatforms: cap(
    'campaign:read',
    'campaign:write',
    'ad-group:read',
    'ad-group:write',
    'ad:read',
    'ad:write',
    'stats:read',
    'audience:read',
    'audience:write',
    'budget:read',
    'budget:write',
    'keyword:read',
  ),
  CommsCollaboration: cap(
    'message:read',
    'message:write',
    'channel:read',
    'channel:write',
    'user:read',
    'email:read',
    'email:write',
    'meeting:read',
    'meeting:write',
    'calendar:read',
    'calendar:write',
    'file:read',
    'file:write',
  ),
  ProjectsWorkMgmt: cap(
    'project:read',
    'project:write',
    'task:read',
    'task:write',
    'task:assign',
    'board:read',
    'sprint:read',
    'sprint:write',
    'milestone:read',
    'comment:read',
    'comment:write',
    'label:read',
    'time:read',
    'time:write',
  ),
  DocumentsEsign: cap(
    'document:read',
    'document:write',
    'folder:read',
    'folder:write',
    'share:write',
    'permission:read',
    'permission:write',
    'esign:read',
    'esign:write',
    'template:read',
    'template:write',
    'audit:read',
  ),
  AnalyticsBi: cap(
    'dashboard:read',
    'report:read',
    'report:write',
    'report:export',
    'query:read',
    'query:write',
    'datasource:read',
    'datasource:write',
    'dataset:read',
    'dataset:write',
    'metric:read',
    'user:read',
    'share:write',
  ),
  MonitoringIncident: cap(
    'alert:read',
    'alert:write',
    'incident:read',
    'incident:write',
    'schedule:read',
    'schedule:write',
    'escalation:read',
    'service:read',
    'statuspage:write',
    'maintenance:read',
    'notification:write',
  ),
  ComplianceGrc: cap(
    'control:read',
    'control:write',
    'risk:read',
    'risk:write',
    'policy:read',
    'policy:write',
    'audit:read',
    'audit:write',
    'finding:read',
    'finding:write',
    'evidence:read',
    'evidence:write',
    'framework:read',
    'framework:write',
  ),
  RoboticsActuation: cap(
    'robot:execute_action',
    'robot:cancel_action',
    'robot:stop',
    'robot:estop_request',
    'robot:get_state',
    'robot:get_diagnostics',
    'actuator:set_state',
    'actuator:get_state',
  ),
} as const satisfies Record<PortFamily, readonly PortCapability[]>;

export function portFamilyCapabilities(family: PortFamily): readonly PortCapability[] {
  return PORT_FAMILY_CAPABILITIES[family];
}

export function isAllowedPortCapability(
  family: PortFamily,
  value: string,
): value is PortCapability {
  return portFamilyCapabilities(family).includes(value as PortCapability);
}
