name: Bug Report
description: Report a defect in Portarium behavior.
title: 'bug: '
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include clear reproduction steps and observed vs expected behavior.
  - type: input
    id: area
    attributes:
      label: Area
      description: Which area is affected?
      placeholder: 'control-plane API, cockpit UI, integration adapter, docs'
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Provide exact steps to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include OS, Node version, and relevant runtime flags.
      placeholder: 'Windows 11, Node 22.x, Docker Compose 2.x'
    validations:
      required: true
  - type: input
    id: evidence
    attributes:
      label: Evidence Links (optional)
      description: Logs, screenshots, traces, or CI run links.
      placeholder: 'https://...'
