groups:
  - name: portarium-pack-regression-detectors
    interval: 1m
    rules:
      - alert: PortariumPackRunFailureRateRegression
        expr: |
          (
            sum by (pack_id) (rate(portarium_run_failed_total[15m]))
            /
            clamp_min(sum by (pack_id) (rate(portarium_run_started_total[15m])), 0.0001)
          ) > 0.05
        for: 15m
        labels:
          severity: warning
          detector: regression
        annotations:
          summary: 'Run failure-rate regression detected for pack {{ $labels.pack_id }}'
          description: 'Run failure ratio exceeded 5% for 15 minutes.'

      - alert: PortariumPackRunLatencyRegressionP95
        expr: |
          histogram_quantile(
            0.95,
            sum by (le, pack_id) (rate(portarium_run_duration_ms_bucket[15m]))
          ) > 2000
        for: 15m
        labels:
          severity: warning
          detector: regression
        annotations:
          summary: 'Run latency regression detected for pack {{ $labels.pack_id }}'
          description: 'Run p95 latency exceeded 2000 ms for 15 minutes.'

      - alert: PortariumPackActionLatencyRegressionP95
        expr: |
          histogram_quantile(
            0.95,
            sum by (le, pack_id, action_operation) (rate(portarium_action_duration_ms_bucket[15m]))
          ) > 1500
        for: 10m
        labels:
          severity: warning
          detector: regression
        annotations:
          summary: 'Action latency regression detected for pack {{ $labels.pack_id }}'
          description: 'Action p95 latency exceeded 1500 ms for 10 minutes.'

      - alert: PortariumPackTelemetryLabelCoverageRegression
        expr: |
          sum(rate(portarium_run_started_total{pack_id=\"\"}[10m])) > 0
        for: 10m
        labels:
          severity: critical
          detector: regression
        annotations:
          summary: 'Pack telemetry label coverage regression detected'
          description: 'Observed run metrics without pack_id label for 10 minutes.'
