import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..', '..');

const manifestPath = path.join(repoRoot, 'research', 'manifest.json');
const pinsPath = path.join(repoRoot, 'research', 'pins.json');
const indexPath = path.join(repoRoot, 'docs', 'research', 'index.md');

function readJson(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing file: ${path.relative(repoRoot, filePath)}`);
  }
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function normalizeNotesPath(source) {
  if (typeof source.notesPath === 'string' && source.notesPath.trim().length > 0) {
    return source.notesPath.trim();
  }
  return path.posix.join('docs', 'research', 'sources', `${source.id}.md`);
}

function formatPinned(pins, id) {
  const pin = pins?.pinned?.[id];
  if (!pin?.commit) return 'TBD';
  return pin.commit.slice(0, 12);
}

function escapePipes(value) {
  return String(value).replaceAll('|', '\\|');
}

function main() {
  const manifest = readJson(manifestPath);
  const pins = readJson(pinsPath);

  if (manifest?.version !== 1 || !Array.isArray(manifest.sources)) {
    throw new Error(`Invalid manifest format: ${path.relative(repoRoot, manifestPath)}`);
  }
  if (pins?.version !== 1 || pins.pinned === undefined || typeof pins.pinned !== 'object') {
    throw new Error(`Invalid pins format: ${path.relative(repoRoot, pinsPath)}`);
  }

  const sources = manifest.sources;

  const lines = [];
  lines.push('<!--');
  lines.push('This file is generated by `npm run research:index`.');
  lines.push('Do not edit by hand.');
  lines.push('-->');
  lines.push('');
  lines.push('# Research Index');
  lines.push('');
  lines.push('Tracks upstream sources being studied, their pinned commits, and their notes.');
  lines.push('');
  lines.push(`- Manifest: \`${path.posix.join('research', 'manifest.json')}\``);
  lines.push(`- Pins: \`${path.posix.join('research', 'pins.json')}\``);
  lines.push(`- Local clones (gitignored): \`${path.posix.join('research', 'sources')}/\``);
  lines.push('');
  lines.push('## Sources');
  lines.push('');

  if (sources.length === 0) {
    lines.push(
      `No sources yet. Add entries to \`${path.posix.join('research', 'manifest.json')}\` and run \`npm run research:sync\`.`,
    );
    lines.push('');
  } else {
    lines.push('| ID | Name | Repo | Pinned | Notes |');
    lines.push('|---|---|---|---|---|');

    for (const source of sources) {
      const id = escapePipes(source.id);
      const name = escapePipes(source.name);
      const repo = escapePipes(source.repo);
      const pinned = escapePipes(formatPinned(pins, source.id));
      const notesPath = normalizeNotesPath(source);
      // Relative link within the repo; keep it simple and stable.
      const notesLink = escapePipes(notesPath);

      lines.push(`| \`${id}\` | ${name} | \`${repo}\` | \`${pinned}\` | \`${notesLink}\` |`);
    }

    lines.push('');
  }

  ensureDir(path.dirname(indexPath));
  fs.writeFileSync(indexPath, `${lines.join('\n')}\n`, 'utf8');
}

main();
